name: Build Bundle

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          cd cloudflare-python
          python -m pip install --upgrade pip
          pip install pyinstaller requests python-dotenv

      - name: Build executable
        run: |
          cd cloudflare-python
          # Add encoding declaration to the script (macOS version)
          sed -i '' '1i\
          # -*- coding: utf-8 -*-
          ' cloudflare.py
          # Build with explicit UTF-8 encoding
          PYTHONIOENCODING=utf8 pyinstaller --onefile cloudflare.py
          # Make the binary executable
          chmod +x dist/cloudflare

      - name: Prepare workflow structure
        run: |
          mkdir -p workflow/cloudflare-python/dist
          cp cloudflare-python/dist/cloudflare workflow/cloudflare-python/dist/
          chmod +x workflow/cloudflare-python/dist/cloudflare
          cp info.plist workflow/
          cp icon.png workflow/

      - name: Create workflow archive
        run: |
          cd workflow
          zip -r ../Cloudflare-create.alfredworkflow ./*

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}-bundle
          files: Cloudflare-create.alfredworkflow 