name: Release Alfred Workflow

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Prepare workflow structure
        run: |
          mkdir -p workflow/cloudflare-python
          # Add shebang and make executable
          echo '#!/usr/bin/env python3' > workflow/cloudflare-python/cloudflare
          cat cloudflare-python/cloudflare.py >> workflow/cloudflare-python/cloudflare
          chmod +x workflow/cloudflare-python/cloudflare
          # Install dependencies directly in the workflow directory
          cd workflow/cloudflare-python
          pip install --target=. requests

      - name: Create workflow archive
        run: |
          cd workflow
          zip -r ../Cloudflare.alfredworkflow ./*

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: Cloudflare.alfredworkflow
          generate_release_notes: true 