name: Release Alfred Workflow

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          cd cloudflare-python
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Create spec file
        run: |
          cd cloudflare-python
          echo 'block_cipher = None
          a = Analysis(
              ["cloudflare.py"],
              pathex=["."],
              binaries=[],
              datas=[],
              hiddenimports=["requests", "urllib3", "certifi", "idna", "charset_normalizer"],
              hookspath=[],
              hooksconfig={},
              runtime_hooks=[],
              excludes=[],
              win_no_prefer_redirects=False,
              win_private_assemblies=False,
              cipher=block_cipher,
              noarchive=False,
          )
          pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
          exe = EXE(
              pyz,
              a.scripts,
              a.binaries,
              a.zipfiles,
              a.datas,
              [],
              name="cloudflare",
              debug=False,
              bootloader_ignore_signals=False,
              strip=False,
              upx=True,
              upx_exclude=[],
              runtime_tmpdir=None,
              console=True,
              disable_windowed_traceback=False,
              argv_emulation=False,
              target_arch=None,
              codesign_identity=None,
              entitlements_file=None,
          )' > cloudflare.spec

      - name: Build executable
        run: |
          cd cloudflare-python
          pyinstaller cloudflare.spec

      - name: Prepare workflow structure
        run: |
          mkdir -p workflow/cloudflare-python
          cp cloudflare-python/dist/cloudflare workflow/cloudflare-python/
          chmod +x workflow/cloudflare-python/cloudflare
          cp info.plist workflow/
          if [ -f prefs.plist ]; then cp prefs.plist workflow/; fi

      - name: Build Alfred workflow
        id: alfred_builder
        uses: com30n/build-alfred-workflow@v1.2.3
        with:
          workflow_dir: workflow
          output_file: Cloudflare.alfredworkflow

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.alfred_builder.outputs.workflow_file }}
          generate_release_notes: true 